# version: "3.9"
# services:
#   frontend:
#     build: .
#     ports:
#       - "3000:3000"
#     networks:
#       - shared_network

# networks:
#   shared_network:
#     driver: bridge  

version: '3'
services:
  frontend:
    build: .
    container_name: nextjs_app
    restart: always
    ports:
      - "3000:3000"
  
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend