version: "3.9"
services:
  frontend:
    build: .
    ports:
      - "80:3000"


  nginx:
    image: nginx:alpine
    container_name: maiddy-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./build:/usr/share/nginx/html
    depends_on:
      - frontend
