# Generated by Django 4.2.16 on 2025-01-08 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("diaries", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="diary",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diaries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="diary",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment",
                to="diaries.diary",
            ),
        ),
    ]
