# Generated by Django 4.2.16 on 2025-01-08 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diaries", "0003_delete_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diary",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
